project:
  type: website

website:
  title: "  "
  favicon: "/img/cropped-cropped-flourish-1-270x270.gif"
  margin-header: |
    ![](/img/CollegeLockupStacked.jpg)
  navbar:
    background: "#62259d"
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: "Modules"
        menu: 
          - modules/w2-lurking.qmd
          - modules/w3-timelines.qmd
      - text: "Resources"
        menu:
          - resources/mastodon.qmd
    right:
      - icon: envelope
        aria-label: envelope
        href: mailto:martin_roberts@emerson.edu
      - icon: mastodon
        aria-label: mastodon
        href: https://merveilles.town/@dokoissho
      - icon: github
        aria-label: github
        href: https://github.com/mroberts1
      - icon: facebook
        aria-label: facebook
        href: https://facebook.com/mr05301
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/mroberts_VMA
format: 
  html:
    toc: true
    toc-depth: 3  
    toc-location: right
    toc-title: '   '
    theme: 
      light: ember.scss
      dark: slate
    css: custom.scss
    fontsize: 1em
    linestretch: 1.5
    smooth-scroll: true
    linkcolor: "#62259d"
    page-layout: article
  pdf:
    geometry:
      - top=30mm
      - left=30mm
      - heightrounded
    mainfont: "Optima"
    linestretch: 1.2
    papersize: letter
    colorlinks: true
fig-responsive: true
image-alt: " "
execute:
  echo: false
  editor: visual
