project:
  type: website

website:
  title: ""
  navbar:
    background: "#62259d"
    search: false
    right:
      - text: "Home"
        file: index.qmd
      - text: "Lectures"
        menu: 
          - lectures/lurking.qmd
format:
  html:
    toc: true  
    toc-depth: 3  
    toc-location: left
    toc-title: ' '
    theme: 
      light: ember.scss
      dark: slate
    css: custom.scss
    fontsize: 1em
    linestretch: 1.5
    smooth-scroll: true
    linkcolor: "#706258"
  pdf:
    geometry:
    - top=30mm
    - left=30mm 
margin-header: | 
    ![](img/Purple-Restricted-Flourish-400px.png){size="50%"}
page-layout: article
docx: default
fig-responsive: true
link-external-newwindow: false
embed-resources: false
editor: visual
execute:
  freeze: auto