project:
  type: website

website:
  title: "   VM303-01 Studies in Digital Media & Culture"
  navbar:
    background: "#62259d"
    search: true
    left:
      - text: "Pages"
        menu: 
          - pages/lurking.qmd
    right:
      - icon: envelope
        href: mailto:martin_roberts@emerson.edu
      - icon: mastodon
        aria-label: mastodon
        href: https://merveilles.town/@dokoissho
      - icon: github
        href: https://github.com/mroberts1
      - icon: facebook
        href: https://facebook.com/mr05301
      - icon: twitter
        href: https://twitter.com/mroberts_VMA

format:
  html:
    toc: true  
    toc-depth: 3  
    toc-location: left
    toc-title: ' '
    theme: 
      light: ember.scss
      dark: slate
    css: custom.scss
    fontsize: 1em
    linestretch: 1.5
    smooth-scroll: true
    linkcolor: "#706258"
  pdf:
    geometry:
    - top=30mm
    - left=30mm 
page-layout: article
docx: default
fig-responsive: true
link-external-newwindow: false
embed-resources: false
editor: visual
execute:
  freeze: auto