project:
  type: website

website:
  title: ""
  navbar:
    background: light
    search: false
    right:
      - text: "Home"
        file: index.qmd
      - text: "Lectures"
        menu: 
          - lectures/lurking.qmd
format:
  html:
    toc: true  
    toc-depth: 3  
    toc-location: left
    toc-title: ' '
    theme: 
      light: ember.scss
      dark: slate
    css: styles.css
    fontsize: 1em
    linestretch: 1.5
    smooth-scroll: true
  pdf:
    geometry:
    - top=30mm
    - left=30mm 
    
page-layout: article
docx: default
fig-responsive: true
link-external-newwindow: false
embed-resources: false
editor: visual
execute:
  freeze: auto